# Generated by Django 3.0.8 on 2020-08-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='token',
            field=models.CharField(help_text='令牌', max_length=255, verbose_name='令牌'),
        ),
    ]
